# -*- coding: utf-8 -*-
"""tripadv_scrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1polPIIJzvXPvbx2ntRadjqoCVVIUiCnu
"""

!pip install tripadvisorapi -q
from tripadvisorapi.api import TripadvisorApi
import json
import pandas as pd

cities = [
    "Amsterdam", "Athens", "Berlin", "Bratislava", "Brussels",
    "Bucharest", "Budapest", "Copenhagen", "Dublin", "Helsinki",
    "Lisbon", "Ljubljana", "London", "Luxembourg", "Madrid", "Oslo", "Paris",
    "Prague", "Reykjavik", "Riga", "Rome",
    "Stockholm", "Tallinn", "Vienna", "Warsaw",
    "Seoul", "Singapore", "Hong Kong", "Sydney", "Melbourne",
    "Cape Town", "Johannesburg", "Bangkok", "Kuala Lumpur", "New Delhi",
    "Hanoi", "Santiago", "Dubai", "Cairo", "Riyadh",
    "Tel Aviv", "Abu Dhabi", "Doha", "Karachi", "Mumbai",
    "Nairobi", "Brisbane", "Perth", "Montreal", "Toronto",
    "Vancouver", "San Francisco", "Chicago", "Houston", "Miami",
    "New York", "Tokyo", "Shanghai", "São Paulo", "Mexico City",
    "Cairo", "Mumbai", "Beijing", "Dhaka", "Osaka", "Buenos Aires", "Chongqing", "Istanbul", "Kolkata",
    "Manila", "Lagos", "Rio de Janeiro", "Tianjin", "Kinshasa",
    "Guangzhou", "Los Angeles", "Moscow", "Shenzhen", "Bangalore",
    "Ho Chi Minh City", "Jakarta", "Lima", "Tehran", "Bogotá"
]

len(cities)

# Initialize API with your API key
key = "E4D278B517604D14A77120B9E794CFB9"
api = TripadvisorApi(key)

data = pd.DataFrame(columns=['rev_id','loc_id','loc_name','city', 'review','rating'])

for city in cities:
  locations_response = api.location_search(searchQuery=city, category='attraction')
  locations_json = json.loads(locations_response.text)['data']
  locations = {}

  for i in range(len(locations_json)):
    try:
      locations[locations_json[i]['location_id']] = locations_json[i]['name'], locations_json[i]['address_obj']['city']
    except:
      pass

  for id in locations.keys():
    reviews = api.location_reviews(id)
    location_reviews = json.loads(reviews.text)
    for review_num in range(len(location_reviews['data'])):
      review_dict = {'rev_id': location_reviews['data'][review_num]['id'],
                'loc_id': id,
                'loc_name': locations[id][0],
                'city': locations[id][1],
                'review': location_reviews['data'][review_num]['text'],
                'rating':location_reviews['data'][review_num]['rating']}
      data.loc[len(data.index)] = review_dict

data

data.to_csv("tridadv_reviews.csv")

data[data['rating']<=3].to_csv("tripadv_badreviews.csv")